# Generated by Django 3.2.4 on 2021-08-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
